import type { NextPage } from 'next';
import Head from 'next/head';
import { prisma } from '../client/db';

const Home: NextPage = (props: any) => {
  const tasks = JSON.parse(props.tasks);

  return (
    <div className='h-screen flex flex-col justify-center items-center bg-slate-800'>
      <Head>
        <title>fior-t3-todo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className='p-4 text-6xl font-extrabold text-slate-200'>Welcome to fior-t3-todo</h1>
      </main>
      <div>
        {tasks &&
          tasks.map((task: any) => (
            <div key={task.id} className='text-2xl flex items-center'>
              <input id={task.id} type='checkbox' checked={task.isDone} className='m-3' />
              <label htmlFor={task.id}>{task.name}</label>
            </div>
          ))}
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const tasks = await prisma.task.findMany();

  return {
    props: {
      tasks: JSON.stringify(tasks),
    },
  };
};
