import { task } from '@prisma/client';
import type { NextPage } from 'next';
import Head from 'next/head';
import Task from '../components/Task';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
  const tasks = trpc.useQuery(['task.get-all']);

  if (tasks.isLoading || !tasks.data) {
    return <div>Loading...</div>;
  }

  return (
    <div className='h-screen flex flex-col justify-center items-center bg-slate-800'>
      <Head>
        <title>fior-t3-todo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1 className='p-4 text-6xl font-extrabold text-slate-200'>Welcome to fior-t3-todo</h1>
      <div>
        {tasks.data
          .sort((taskA, taskB) => Number(taskA.isDone) - Number(taskB.isDone) || taskB.createdAt.getTime() - taskA.createdAt.getTime())
          .map((task: task) => (
            <Task key={task.id} id={task.id} createdAt={task.createdAt} name={task.name} isDone={task.isDone} />
          ))}
      </div>
    </div>
  );
};

export default Home;
